apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}-config
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  mongod.conf: |
{{ .Values.mongodb.configuration | indent 4 }}