{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.rootPassword }}
  mongodb-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.password }}
  mongodb-password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}